### ISSUE TITLE
How to deploy other than localhost

### ISSUE THREAD

**Issue by arminus** [FormPress/FormPress#1]
I'm trying to test this on a remote server. Docker containers start ok and w/o errors or warnings, but when I tried to access `http://<myip>:3000`, the page fails to load because it tries to connect to http://**localhost**:3001/api/server/capabilities which obviously can't work.

Tried setting
```
FE_BACKEND=http://<myip>:3001
```
in the .env, no change

**Comment by afroximity** [comment]
Hey @arminus, thank you for notifying about the problem!

https://github.com/FormPress/FormPress/blob/b7cf93c83edffb592deb421289394faf873ff62e/frontend/src/index.js#L14C1-L15C49

In the link above, you will notice two lines which sets FE_BACKEND and FE_FRONTEND hard-coded to localhost. You are right, this is an erroneous approach because it doesn't take your .env changes into account. Modifying these lines with your remote server info will fix your problem (hopefully).

`global.env.FE_BACKEND = 'http://localhost:3001'`
`global.env.FE_FRONTEND = 'http://localhost:3000'`


But please keep in mind that we use Docker Compose for local development only. It is a development server and will not be as performant as a production build.

**Comment by korkmazOmer** [comment]
I believe @afroximity is right. I tried to make these variables as optional, it seems I made a mistake in logic. I will fix it in next release.

Keep in my if you are using that way, you may have performance and security issues. You should check code base for development flags. Best luck.

**Comment by arminus** [comment]
Thanks for the quick response. Yes, that works. I do wonder though, what's the recommended approach to serve this as production build if not with docker compose? And how would you put that behind a reverse proxy given what is presently being done in the `if (global.env.FP_ENV === 'production')` block?

**Comment by korkmazOmer** [comment]
We use terraform and gcp(gke) for production build. You can check [infra/example folder](https://github.com/FormPress/FormPress/tree/master/infra/example) for detailed information.

**Comment by arminus** [comment]
I can create a form, but a preview or view of the published form only shows a blank page since `http://<myip>:3000/editor/1/preview` again calls `http://localhost:3001/runtime/form.js`

**Comment by afroximity** [comment]
Check development flags in the codebase for these kind of problems. In a few places, you will see it defaults to `localhost`.


https://github.com/FormPress/FormPress/blob/master/backend/middleware/api.js#L33

`const BACKEND = FP_ENV === 'development' ? `${FP_HOST}:${port}` : FP_HOST`


This line in api.js is the definition of backend. 

`http://localhost:3001/runtime/form.js`

is actually 

`${BACKEND}/runtime/form.js`

This comes from the declaration in Dockerfile.development in backend folder.
Try setting your FP_HOST to your ip in .env file.

**Comment by arminus** [comment]
Thanks, but I think hacking it like this might not be the way to go. You guys use docker just for dev deployment, for my case, terraform and kubernetes for server deployment is kind of overkill so well...
